### ISSUE TITLE
Double checking correctness of default behavior of propensity.func() when NULL

### ISSUE THREAD

**Issue by AaronPotvien** [jaredhuling/personalized#13]
With the multiple treatments update in place, is the default behavior of `propensity.func()` within `fit.subgroup()` correct for its return of `pi.x`? 

For instance, when `n.trts == 2`, all subjects get assigned the same value of `mean.trt`. However, when there are more, say `n.trts == 3`, then there are 3 different possible values assigned (each getting the mean of their respective category of membership).

This seems like a disconnect (going from 1 to 2 treatments but going from 1 to 3 unique values of `pi.x`).

Doesn't the generalized version already provide the right calculation when `n.trts == 2?`. Could the following block be removed from `propensity.func()` without breaking anything?

        if (n.trts == 2)
        {
            mean.trt <- mean(trt == unique.trts[2L])
            propensity.func <- function(trt, x) rep(mean.trt, length(trt))
        } else

For reference, the entire block of code I'm referring to is this:

    if (is.null(propensity.func))
    {
        if (n.trts == 2)
        {
            mean.trt <- mean(trt == unique.trts[2L])
            propensity.func <- function(trt, x) rep(mean.trt, length(trt))
        } else
        {
            mean.trt <- numeric(n.trts)
            for (t in 1:n.trts)
            {
                mean.trt[t] <- mean(trt == unique.trts[t])
            }
            propensity.func <- function(trt, x)
            {
                pi.x <- numeric(length(trt))
                for (t in 1:n.trts)
                {
                    which.t       <- trt == unique.trts[t]
                    pi.x[which.t] <- mean(which.t)
                }

                pi.x
            }
        }
    }

**Comment by jaredhuling** [comment]
This is fine. Note how in the weighting method you divide each term by $T_i\pi(x_i) + (1 - T_i) / 2$, where $T_i \in \{1, -1\}$. This is just $Pr(T = T_i | X = x_i)$. The idea is the same for multiple treatments, you are dividing by the probability of receiving the treatment you actually received. In the multiple treatment case I allow the user to specify a vector of probabilities (which must be the probability of receiving what they received) or a matrix of probabilities with each column being the probability of receiving a particular treatment, which i then just convert to the first thing
